### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Flusinerd** [RUBO-Repair-Cafe/Boerse-App#1]
- [ ] Create Listing
- [ ] Edit Listing
- [ ] Own Listings
- [ ] Chat
- [ ] Listing as sold / reserved
- [ ] Tags subscription
- [ ] Push Notifications Tag subscription
- [ ] Push Notifications Chat Messages
- [ ] Image Upload
- [ ] Image Display

- [ ] German Localization
